services:
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    environment:
      POSTGRES_DB: behavior_coach
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - prisma-network

  server:
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app/src
      - ./server.ts:/usr/src/app/server.ts
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./prisma:/usr/src/app/prisma
    depends_on:
      postgres_db:
        condition: service_healthy
      localstack:
        condition: service_started
    env_file:
      - .env
    networks:
      - prisma-network

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - .env
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      server:
        condition: service_started

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - prisma-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  prisma-network:
    name: prisma-network

volumes:
  pgadmin-data:
